 

#1. *this is the code for naive bayes.*

#2.  in this code the x_train and y_train is given as input in the form of dataframe. 

#3.the solution function extracts the dictionary from the dataframe and valuable information can be listed using the dictionary.

#4. now in the predict function the dictionary extrated from the training datasets and the x_test is provides to the function.  

#5. **(meanwhile the testing data is provided in the form of numpy array)**

#6. the predict function uses the naive bayes algorithm and predicts the most accurate y_test data 

In [ ]:
#this is the code for naive bayes.
#in this code the x_train and y_train is given as input in the form of dataframe.
#the solution function extracts the dictionary from the dataframe and valuable information can be listed using the dictionary.
#now in the predict function the dictionary extrated from the training datasets and the x_test is provides to the function.
#**(meanwhile the testing data is provided in the form of numpy array)
#the predict function uses the naive bayes algorithm and predicts the most accurate y_test data 

In [ ]:
from sklearn import datasets
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
#the program to find the dictionary if the data are given in DataFrame format
def solution(x_train, y_train):
  result={}
  result["total data"]=len(y_train)
  all_class=set(y_train)
  for perticular_class in all_class:
    result[perticular_class]={}
    #for all the class i need to get the rows corresponding to each class
    #single class here is defined by perticular class
    row_index_of_perticular_class=y_train[y_train==perticular_class].index
    result[perticular_class]["total count"]=len(row_index_of_perticular_class)
    x_train_class=x_train.iloc[row_index_of_perticular_class]
    y_train_class=y_train.iloc[row_index_of_perticular_class]
    # now lets traverse through each feature in the x_train feature
    for j in range(x_train_class.shape[1]):
      result[perticular_class][j]={}
      for k in range(y_train_class.shape[0]):
        if x_train_class.iat[k,j] in result[perticular_class][j]:
          result[perticular_class][j][x_train_class.iat[k,j]]+=1
        else:
          result[perticular_class][j][x_train_class.iat[k,j]]=1

  return result

In [ ]:
def probability(dictionary, x, perticular_class):
  total_count=dictionary[perticular_class]['total count']
  total_data=dictionary["total data"]
  probability=np.log(total_count)-np.log(total_data)
  features=list(dictionary[perticular_class].keys())
  features.remove("total count")
  c=0
  for feature in features:
    x_entity=x[c]
    # print(x_entity)
    #now i am adding one so as to handle the border cases as well
    count_with_perticular_value=0
    if (x_entity in dictionary[perticular_class][feature]):
      count_with_perticular_value=dictionary[perticular_class][feature][x_entity]+1
    else:
      count_with_perticular_value=1
    count_of_the_feature=dictionary[perticular_class]["total count"]+len(dictionary[perticular_class][feature].keys())
    probability+=np.log(count_with_perticular_value)-np.log(count_of_the_feature)
    c+=1

  return probability

In [ ]:
def predictSinglePoint(dictionary, x):
  all_class=list(dictionary.keys())
  all_class.remove("total data")
  p=-1000
  best_class=-1
  for perticular_class in all_class:
      probability_of_this_class=probability(dictionary, x ,perticular_class)
      if (probability_of_this_class>p):
        best_class=perticular_class
        p=probability_of_this_class
  return best_class


In [ ]:
#lets say we want to predict the result for the x_test
#lets say we have x_test in the form of numpy array
def predict(dictionary, x_test):
  y_pred=[]
  for x in x_test:
    x_class=predictSinglePoint(dictionary, x)
    y_pred.append(x_class)
  return y_pred


lets try for a datasets where the values for the parameter and the target are chosen at random

In [1]:

dict={
    "f1":["yes","no","no","no","no","yes","no","no","yes","no"],
    "f2":["No","Yes","No","Yes","Yes","No","Yes","Yes","No","No"],
    "class":[1,2,1,1,2,2,3,1,3,3]
}

In [2]:
import pandas as pd
graph=pd.DataFrame(dict)
graph

f1   f2  class
0  yes   No      1
1   no  Yes      2
2   no   No      1
3   no  Yes      1
4   no  Yes      2
5  yes   No      2
6   no  Yes      3
7   no  Yes      1
8  yes   No      3
9   no   No      3

In [ ]:
x_train=pd.DataFrame(dict)
y_train=x_train["class"]
x_train=x_train.drop(columns=["class"])
x_train

f1   f2
0  yes   No
1   no  Yes
2   no   No
3   no  Yes
4   no  Yes
5  yes   No
6   no  Yes
7   no  Yes
8  yes   No
9   no   No

In [ ]:
y_train

0    1
1    2
2    1
3    1
4    2
5    2
6    3
7    1
8    3
9    3
Name: class, dtype: int64

In [ ]:
dictionary=solution(x_train, y_train)
dictionary

{'total data': 10,
 1: {'total count': 4, 0: {'yes': 1, 'no': 3}, 1: {'No': 2, 'Yes': 2}},
 2: {'total count': 3, 0: {'no': 2, 'yes': 1}, 1: {'Yes': 2, 'No': 1}},
 3: {'total count': 3, 0: {'no': 2, 'yes': 1}, 1: {'Yes': 1, 'No': 2}}}

In [ ]:
dict_test={
    "f1":["yes","yes","no","no","no"],
    "f2":["Yes","No","Yes","Yes","No"]
}

In [ ]:
x_test_dataframe=pd.DataFrame(dict_test)
x_test_dataframe

f1   f2
0  yes  Yes
1  yes   No
2   no  Yes
3   no  Yes
4   no   No

In [ ]:
x_test=x_test_dataframe.to_numpy()
x_test

array([['yes', 'Yes'],
       ['yes', 'No'],
       ['no', 'Yes'],
       ['no', 'Yes'],
       ['no', 'No']], dtype=object)

In [ ]:
#lets just predict the value for random test case
#well it wont be very accurate because the data is minimal and the observations are assigned randomly, but it works on the algorithm of naive bayes
predict(dictionary, x_test)

yes
Yes
yes
Yes
yes
Yes
yes
No
yes
No
yes
No
no
Yes
no
Yes
no
Yes
no
Yes
no
Yes
no
Yes
no
No
no
No
no
No


[2, 3, 1, 1, 1]

In [ ]:
def makeLabelled(column):
    second_limit = column.mean()
    first_limit = 0.5 * second_limit
    third_limit = 1.5*second_limit
    for i in range (0,len(column)):
        if (column[i] < first_limit):
            column[i] = 0
        elif (column[i] < second_limit):
            column[i] = 1
        elif(column[i] < third_limit):
            column[i] = 2
        else:
            column[i] = 3
    return column

In [ ]:
from sklearn import datasets
iris=datasets.load_iris()
x_data=iris.data
y_data=iris.target


In [ ]:
x_data[:3]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

lets try for the dataset from the sklearn library

In [ ]:
for i in range(0,x_data.shape[-1]):
  x_data[:,i] = makeLabelled(x_data[:,i])

In [ ]:

from sklearn.model_selection import train_test_split
x_train_data, x_test_data, y_train_data, y_test_data=train_test_split(x_data, y_data,test_size=0.25,random_state=0)
x_train_data.shape, x_test_data.shape, y_train_data.shape, y_test_data.shape

((112, 4), (38, 4), (112,), (38,))

In [ ]:
x_train_data=pd.DataFrame(x_train_data)
y_train_data=pd.Series(y_train_data)

In [ ]:
dictionary_data=solution(x_train_data, y_train_data)
dictionary_data
# y_pred_data=predict(dictionary_data, x_test_data)
# confusion_matrix(y_pred_data, y_test_data)

{'total data': 112,
 0: {'total count': 37,
  0: {1.0: 37},
  1: {2.0: 31, 1.0: 6},
  2: {0.0: 37},
  3: {0.0: 36, 1.0: 1}},
 1: {'total count': 34,
  0: {2.0: 15, 1.0: 19},
  1: {1.0: 28, 2.0: 6},
  2: {2.0: 28, 1.0: 6},
  3: {2.0: 25, 1.0: 8, 3.0: 1}},
 2: {'total count': 41,
  0: {2.0: 37, 1.0: 4},
  1: {1.0: 26, 2.0: 15},
  2: {2.0: 24, 3.0: 17},
  3: {3.0: 37, 2.0: 4}}}

In [ ]:
x_test_data=np.array(x_test_data)


In [ ]:
x_test_data,y_test_data

(array([[1., 1., 2., 3.],
        [2., 1., 2., 1.],
        [1., 2., 0., 0.],
        [2., 1., 3., 3.],
        [1., 2., 0., 0.],
        [2., 2., 3., 3.],
        [1., 2., 0., 0.],
        [2., 2., 2., 2.],
        [2., 1., 2., 2.],
        [2., 1., 2., 2.],
        [2., 1., 2., 2.],
        [2., 2., 2., 2.],
        [2., 1., 2., 2.],
        [2., 1., 2., 2.],
        [2., 1., 2., 2.],
        [1., 2., 0., 0.],
        [2., 1., 2., 2.],
        [1., 1., 2., 2.],
        [1., 1., 0., 0.],
        [1., 2., 0., 0.],
        [1., 1., 2., 3.],
        [1., 1., 2., 2.],
        [1., 2., 1., 0.],
        [1., 1., 0., 0.],
        [2., 1., 2., 3.],
        [1., 2., 0., 0.],
        [1., 2., 1., 0.],
        [2., 1., 2., 2.],
        [1., 1., 1., 1.],
        [1., 2., 0., 0.],
        [2., 2., 2., 3.],
        [1., 1., 2., 2.],
        [1., 2., 0., 0.],
        [2., 1., 2., 3.],
        [2., 1., 2., 3.],
        [1., 1., 2., 2.],
        [1., 2., 0., 0.],
        [2., 1., 2., 2.]]),
 array([2,

In [ ]:
y_pred_data=predict(dictionary_data, x_test_data)

In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred_data, y_test_data)

array([[13,  0,  0],
       [ 0, 16,  1],
       [ 0,  0,  8]])